# Generated by Django 5.2.8 on 2025-11-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collected_waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry_waste', models.IntegerField(blank=True, max_length=3)),
                ('wet_waste', models.IntegerField(blank=True, max_length=3)),
                ('plastic_waste', models.IntegerField(blank=True, max_length=3)),
                ('medical_waste', models.IntegerField(blank=True, max_length=3)),
                ('E_waste', models.IntegerField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='complaint_portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mob_no', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='driver_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mob_no', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('pin_code', models.CharField(max_length=12)),
                ('ward_no', models.CharField(max_length=12)),
            ],
        ),
    ]
