# Generated by Django 5.2.8 on 2025-11-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_registration',
        ),
        migrations.RenameField(
            model_name='driver_registration',
            old_name='phone',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='driver_registration',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='collected_waste',
            name='remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driver_registration',
            name='mob_no',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver_registration',
            name='pin_code',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver_registration',
            name='ward_no',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collected_waste',
            name='E_waste',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='collected_waste',
            name='dry_waste',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='collected_waste',
            name='medical_waste',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='collected_waste',
            name='plastic_waste',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='collected_waste',
            name='wet_waste',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver_registration',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
